return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.2",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 16,
  height = 108,
  tilewidth = 32,
  tileheight = 32,
  nextobjectid = 508,
  backgroundcolor = { 255, 85, 255 },
  properties = {},
  tilesets = {
    {
      name = "enemy_tileset",
      firstgid = 1,
      tilewidth = 24,
      tileheight = 24,
      spacing = 0,
      margin = 0,
      image = "../gfx/enemy_tileset.png",
      imagewidth = 264,
      imageheight = 24,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 24,
        height = 24
      },
      properties = {},
      terrains = {},
      tilecount = 11,
      tiles = {
        {
          id = 0,
          type = "normal",
          objectGroup = {
            type = "objectgroup",
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 13,
                name = "",
                type = "",
                shape = "rectangle",
                x = 7,
                y = 0,
                width = 10,
                height = 24,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        },
        {
          id = 1,
          type = "hanger",
          properties = {
            ["typeid"] = "hanger"
          },
          objectGroup = {
            type = "objectgroup",
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 24,
                height = 24,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        },
        {
          id = 2,
          type = "sine",
          properties = {
            ["typeid"] = "sine"
          },
          objectGroup = {
            type = "objectgroup",
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 24,
                height = 24,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        },
        {
          id = 3,
          type = "bosscore",
          properties = {
            ["typeid"] = "bosscore"
          }
        },
        {
          id = 4,
          type = "boss",
          properties = {
            ["typeid"] = "boss"
          }
        },
        {
          id = 5,
          type = "player",
          properties = {
            ["typeid"] = "player"
          },
          objectGroup = {
            type = "objectgroup",
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            draworder = "index",
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "rectangle",
                x = 0,
                y = 0,
                width = 24,
                height = 24,
                rotation = 0,
                visible = true,
                properties = {}
              }
            }
          }
        },
        {
          id = 6,
          type = "suicide"
        },
        {
          id = 7,
          type = "shotgun"
        },
        {
          id = 8,
          type = "spray"
        },
        {
          id = 9,
          type = "popcorn"
        },
        {
          id = 10,
          type = "flee"
        }
      }
    }
  },
  layers = {
    {
      type = "imagelayer",
      name = "bg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      image = "../gfx/bg_stub.png",
      properties = {}
    },
    {
      type = "tilelayer",
      name = "Tiles",
      x = 0,
      y = 0,
      width = 16,
      height = 108,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    },
    {
      type = "objectgroup",
      name = "Objects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 91,
          name = "player",
          type = "",
          shape = "rectangle",
          x = 245,
          y = 3435,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 152,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 152,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 344,
          y = 152,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 2976,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 2976,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "-2",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 2880,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 2880,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "1",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 2304,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "2",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 2368,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "2",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 2688,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "1",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 2624,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 2784,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 2784,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 2432,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 218,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 2432,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 2080,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 376,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 1920,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 379,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1920,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 385,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 2112,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 386,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 2112,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 387,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1952,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1952,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 389,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 1952,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 1952,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 391,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1952,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "-3",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 1632,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 394,
          name = "-2",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 1664,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "-3",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1632,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "-2",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1664,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 397,
          name = "-3",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 1632,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 398,
          name = "-2",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1664,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "-3",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 1632,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "-2",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 1664,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "-3",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 1632,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 402,
          name = "-3",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 1632,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 403,
          name = "-2",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1664,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 409,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 2816,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 410,
          name = "-1",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 2624,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "-1",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 2624,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 412,
          name = "-1",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 2624,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 2432,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1632,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 415,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1632,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 2272,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 2272,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 2272,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 422,
          name = "-1",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 2304,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 423,
          name = "-1",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 2304,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "-1",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 2304,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 425,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 2592,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 2592,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 427,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 2592,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1408,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 429,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1280,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 430,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 1280,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 431,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 1120,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 432,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1120,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 433,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1120,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 434,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 896,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 896,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 436,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 896,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 437,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 896,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 896,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 439,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 896,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 704,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 448,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 704,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 449,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 608,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 450,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 608,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {}
        },
        {
          id = 451,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 608,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 452,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 608,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 608,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 454,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 608,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1024,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 456,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 1024,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 457,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1344,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 458,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1184,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 459,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 1184,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 460,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 2976,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 461,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 2976,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 462,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 2784,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 463,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 2784,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 464,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 2624,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 467,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 2432,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 468,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 2304,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 469,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 2016,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 470,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 2016,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 471,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1536,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 472,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 1536,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 473,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 1216,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 474,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1216,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 477,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1344,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 478,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1344,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 479,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 1024,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 482,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 800,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 483,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 800,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 490,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 384,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 491,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 384,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 492,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 384,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 493,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 384,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 494,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 384,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 495,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 384,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 496,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 384,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 497,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 384,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 498,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 288,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 499,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 288,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 500,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 288,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 501,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 288,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 502,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 480,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 503,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 480,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 504,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 480,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 505,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 480,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 506,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 2624,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 507,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 2304,
          width = 24,
          height = 24,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
